export const wordLists = {
    baldurs: [
        'shadowheart',
        'minsc',
        'laezel',
        'karlach',
        'astarion',
        'gale',
        'wyll',
        'halsin',
        'minthara',
        'alfira',
        'losiir'],

    fabrics: [
        'linen',
        'cotton',
        'chiffon',
        'wool',
        'denim',
        'silk',
        'polyester',
        'velvet',
        'crepe',
        'leather',
        'jersey',
        'nylon',
        'satin',
        'lace',
        'rayon',
        'spandex',
        'muslin',
        'bamboo',
        'calico',
        'canvas',
        'cashmere',
        'damask',
        'georgette'],

    arrayMethods: [
        'at',
        'concat',
        'entries',
        'every',
        'fill',
        'filter',
        'find',
        'flat',
        'flatmap',
        'forEach',
        'includes',
        'indexOf',
        'join',
        'keys',
        'map',
        'pop',
        'push',
        'reduce',
        'reverse',
        'shift',
        'slice',
        'some',
        'sort',
        'splice',
        'unshift',
        'with',
    ]
};

